# Generated by Django 3.2.9 on 2021-11-18 00:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('birthday', models.DateField(default=datetime.datetime(2021, 11, 18, 0, 4, 52, 385348, tzinfo=utc), verbose_name='Nascimento')),
                ('date_insc', models.DateField(default=datetime.datetime(2021, 11, 18, 0, 4, 52, 385348, tzinfo=utc), verbose_name='Data de inscrição')),
                ('profession', models.CharField(blank=True, max_length=150, verbose_name='Profissão')),
                ('address', models.CharField(max_length=250, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('tel1', models.IntegerField(blank=True, help_text='Telefone do aluno', max_length=11, null=True, unique=True, verbose_name='Telefone (1)')),
                ('tel2', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Telefone de emergência', max_length=128, null=True, region=None, unique=True, verbose_name='Telefone (2)')),
                ('insta', models.CharField(blank=True, max_length=150, verbose_name='Instagran')),
                ('active', models.BooleanField(default=False, verbose_name='Aluno ativo')),
            ],
        ),
    ]
