# Generated by Django 3.2.9 on 2021-11-18 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Nascimento'),
        ),
        migrations.AlterField(
            model_name='people',
            name='date_insc',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de inscrição'),
        ),
    ]
