# Generated by Django 3.2.9 on 2021-11-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_alter_people_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Endereço'),
        ),
    ]
