# Generated by Django 3.2.9 on 2021-11-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_auto_20211117_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
    ]
