# Generated by Django 3.2.9 on 2021-11-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0007_alter_people_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='tel1',
            field=models.CharField(blank=True, help_text='Telefone do aluno', max_length=11, null=True, unique=True, verbose_name='Telefone (1)'),
        ),
    ]
