# Generated by Django 3.2.9 on 2021-11-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0008_alter_people_tel1'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='day',
            field=models.CharField(choices=[(2, 'Segunda-Feira'), (3, 'Terça-Feira'), (4, 'Quarta-Feira'), (5, 'Quinta-Feira'), (6, 'Sexta-Feira')], default='Segunda-Feira', max_length=30),
        ),
        migrations.AddField(
            model_name='people',
            name='schedule',
            field=models.CharField(choices=[('Manhã', ((1, '07:00 / 08:00'), (2, '08:00 / 09:00'), (3, '09:00 / 10:00'), (4, '10:00 / 11:00'), (5, '11:00 / 12:00'))), ('Noite', ((6, '16:00 / 17:00'), (7, '17:00 / 18:00'), (8, '18:00 / 19:00'), (9, '19:00 / 20:00'), (10, '20:00 / 21:00'), (11, '21:00 / 22:00')))], default='07:00 / 08:00', max_length=30),
        ),
        migrations.AlterField(
            model_name='people',
            name='tel2',
            field=models.CharField(blank=True, help_text='Telefone de emergência', max_length=11, null=True, unique=True, verbose_name='Telefone (2)'),
        ),
    ]
