# Generated by Django 3.2.9 on 2021-11-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0011_auto_20211117_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ('-date_insc',), 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AddField(
            model_name='people',
            name='schedule2',
            field=models.IntegerField(choices=[('Manhã', ((1, 'M1 (07:00 / 08:00)'), (2, 'M2 (08:00 / 09:00)'), (3, 'M3 (09:00 / 10:00)'), (4, 'M4 (10:00 / 11:00)'), (5, 'M5 (11:00 / 12:00)'))), ('Tarde/Noite', ((6, '16:00 / 17:00'), (7, '17:00 / 18:00'), (8, '18:00 / 19:00'), (9, '19:00 / 20:00'), (10, '20:00 / 21:00'), (11, '21:00 / 22:00')))], default=1, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='people',
            name='schedule',
            field=models.IntegerField(choices=[('Manhã', ((1, 'M1 (07:00 / 08:00)'), (2, 'M2 (08:00 / 09:00)'), (3, 'M3 (09:00 / 10:00)'), (4, 'M4 (10:00 / 11:00)'), (5, 'M5 (11:00 / 12:00)'))), ('Tarde/Noite', ((6, '16:00 / 17:00'), (7, '17:00 / 18:00'), (8, '18:00 / 19:00'), (9, '19:00 / 20:00'), (10, '20:00 / 21:00'), (11, '21:00 / 22:00')))], default=1, verbose_name='Horário'),
        ),
    ]
