# Generated by Django 3.2.9 on 2021-11-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0012_auto_20211120_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='schedule2',
            field=models.IntegerField(choices=[('Manhã', ((1, 'M1 (07:00 / 08:00)'), (2, 'M2 (08:00 / 09:00)'), (3, 'M3 (09:00 / 10:00)'), (4, 'M4 (10:00 / 11:00)'), (5, 'M5 (11:00 / 12:00)'))), ('Tarde/Noite', ((6, '16:00 / 17:00'), (7, '17:00 / 18:00'), (8, '18:00 / 19:00'), (9, '19:00 / 20:00'), (10, '20:00 / 21:00'), (11, '21:00 / 22:00')))], default=1, help_text='Horário de aula', verbose_name='Horário (2)'),
        ),
        migrations.AlterField(
            model_name='people',
            name='tel1',
            field=models.CharField(help_text='Telefone do aluno', max_length=11, null=True, unique=True, verbose_name='Telefone (1)'),
        ),
    ]
