# Generated by Django 3.2.9 on 2021-11-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0013_auto_20211120_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='tel1',
            field=models.CharField(help_text='Telefone do aluno', max_length=11, unique=True, verbose_name='Telefone (1)'),
        ),
    ]
