# Generated by Django 3.2.9 on 2021-11-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0014_alter_people_tel1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(2, 'Segunda-Feira'), (3, 'Terça-Feira'), (4, 'Quarta-Feira'), (5, 'Quinta-Feira'), (6, 'Sexta-Feira')], default=2, verbose_name='Dia')),
                ('schedule', models.IntegerField(choices=[('Manhã', ((1, 'M1 (07:00 / 08:00)'), (2, 'M2 (08:00 / 09:00)'), (3, 'M3 (09:00 / 10:00)'), (4, 'M4 (10:00 / 11:00)'), (5, 'M5 (11:00 / 12:00)'))), ('Tarde/Noite', ((6, '16:00 / 17:00'), (7, '17:00 / 18:00'), (8, '18:00 / 19:00'), (9, '19:00 / 20:00'), (10, '20:00 / 21:00'), (11, '21:00 / 22:00')))], default=1, verbose_name='Horário')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ('-day',),
            },
        ),
    ]
