# Generated by Django 3.2.9 on 2021-11-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0015_turmas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turmas',
            options={'ordering': ('day',), 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AlterField(
            model_name='people',
            name='day',
            field=models.IntegerField(choices=[('segunda-feira', 'Segunda-Feira'), ('terça-feira', 'Terça-Feira'), ('quarta-feira', 'Quarta-Feira'), ('quinta-feira', 'Quinta-Feira'), ('sexta-feira', 'Sexta-Feira')], default=2, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='people',
            name='schedule',
            field=models.IntegerField(choices=[('Manhã', ((1, 'M1 (07:00 / 08:00)'), (2, 'M2 (08:00 / 09:00)'), (3, 'M3 (09:00 / 10:00)'), (4, 'M4 (10:00 / 11:00)'), (5, 'M5 (11:00 / 12:00)'))), ('Tarde/Noite', ((6, 'T1 (16:00 / 17:00)'), (7, 'T2 (17:00 / 18:00)'), (8, 'T3 (18:00 / 19:00)'), (9, 'T4 (19:00 / 20:00)'), (10, 'T5 (20:00 / 21:00)'), (11, 'T6 (21:00 / 22:00)')))], default=1, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='people',
            name='schedule2',
            field=models.IntegerField(choices=[('Manhã', ((1, 'M1 (07:00 / 08:00)'), (2, 'M2 (08:00 / 09:00)'), (3, 'M3 (09:00 / 10:00)'), (4, 'M4 (10:00 / 11:00)'), (5, 'M5 (11:00 / 12:00)'))), ('Tarde/Noite', ((6, 'T1 (16:00 / 17:00)'), (7, 'T2 (17:00 / 18:00)'), (8, 'T3 (18:00 / 19:00)'), (9, 'T4 (19:00 / 20:00)'), (10, 'T5 (20:00 / 21:00)'), (11, 'T6 (21:00 / 22:00)')))], default=1, help_text='Horário de aula', verbose_name='Horário (2)'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='day',
            field=models.IntegerField(choices=[('segunda-feira', 'Segunda-Feira'), ('terça-feira', 'Terça-Feira'), ('quarta-feira', 'Quarta-Feira'), ('quinta-feira', 'Quinta-Feira'), ('sexta-feira', 'Sexta-Feira')], default=2, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='schedule',
            field=models.IntegerField(choices=[('Manhã', ((1, 'M1 (07:00 / 08:00)'), (2, 'M2 (08:00 / 09:00)'), (3, 'M3 (09:00 / 10:00)'), (4, 'M4 (10:00 / 11:00)'), (5, 'M5 (11:00 / 12:00)'))), ('Tarde/Noite', ((6, 'T1 (16:00 / 17:00)'), (7, 'T2 (17:00 / 18:00)'), (8, 'T3 (18:00 / 19:00)'), (9, 'T4 (19:00 / 20:00)'), (10, 'T5 (20:00 / 21:00)'), (11, 'T6 (21:00 / 22:00)')))], default=1, verbose_name='Horário'),
        ),
    ]
