# Generated by Django 3.2.9 on 2021-11-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0016_auto_20211121_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='day',
            field=models.CharField(choices=[('segunda-feira', 'Segunda-Feira'), ('terça-feira', 'Terça-Feira'), ('quarta-feira', 'Quarta-Feira'), ('quinta-feira', 'Quinta-Feira'), ('sexta-feira', 'Sexta-Feira')], default=2, max_length=20, verbose_name='Dia'),
        ),
    ]
