# Generated by Django 3.2.9 on 2021-11-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0018_alter_turmas_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='schedule2',
        ),
        migrations.AlterField(
            model_name='people',
            name='day',
            field=models.CharField(choices=[('segunda-feira', 'Segunda-Feira'), ('terça-feira', 'Terça-Feira'), ('quarta-feira', 'Quarta-Feira'), ('quinta-feira', 'Quinta-Feira'), ('sexta-feira', 'Sexta-Feira')], default='segunda-feira', max_length=20, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='people',
            name='schedule',
            field=models.CharField(choices=[('Manhã', (('m1', 'M1 (07:00 / 08:00)'), ('m2', 'M2 (08:00 / 09:00)'), ('m3', 'M3 (09:00 / 10:00)'), ('m4', 'M4 (10:00 / 11:00)'), ('m5', 'M5 (11:00 / 12:00)'))), ('Tarde/Noite', (('t1', 'T1 (16:00 / 17:00)'), ('t2', 'T2 (17:00 / 18:00)'), ('t3', 'T3 (18:00 / 19:00)'), ('t4', 'T4 (19:00 / 20:00)'), ('t5', 'T5 (20:00 / 21:00)'), ('t6', 'T6 (21:00 / 22:00)')))], default='m1', max_length=2, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='day',
            field=models.CharField(choices=[('segunda-feira', 'Segunda-Feira'), ('terça-feira', 'Terça-Feira'), ('quarta-feira', 'Quarta-Feira'), ('quinta-feira', 'Quinta-Feira'), ('sexta-feira', 'Sexta-Feira')], default='segunda-feira', max_length=20, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='schedule',
            field=models.CharField(choices=[('Manhã', (('m1', 'M1 (07:00 / 08:00)'), ('m2', 'M2 (08:00 / 09:00)'), ('m3', 'M3 (09:00 / 10:00)'), ('m4', 'M4 (10:00 / 11:00)'), ('m5', 'M5 (11:00 / 12:00)'))), ('Tarde/Noite', (('t1', 'T1 (16:00 / 17:00)'), ('t2', 'T2 (17:00 / 18:00)'), ('t3', 'T3 (18:00 / 19:00)'), ('t4', 'T4 (19:00 / 20:00)'), ('t5', 'T5 (20:00 / 21:00)'), ('t6', 'T6 (21:00 / 22:00)')))], default='m1', max_length=2, verbose_name='Horário'),
        ),
    ]
