# Generated by Django 3.2.9 on 2021-11-21 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0019_auto_20211121_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmas',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alunos.people'),
        ),
    ]
