# Generated by Django 3.2.9 on 2021-11-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0020_turmas_turma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turmas',
            old_name='turma',
            new_name='alunos',
        ),
    ]
