# Generated by Django 3.2.9 on 2021-11-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0021_rename_turma_turmas_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turmas',
            name='alunos',
        ),
        migrations.AddField(
            model_name='turmas',
            name='alunos',
            field=models.ManyToManyField(blank=True, help_text='Escolha os alunos da turmaprofessores e transfira para a tabela da direita.', to='alunos.People'),
        ),
    ]
