# Generated by Django 3.2.9 on 2021-11-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0022_auto_20211121_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='active',
        ),
        migrations.AddField(
            model_name='people',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=7),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='alunos',
            field=models.ManyToManyField(blank=True, help_text='Escolha os alunos da turma e transfira para a tabela da direita.', to='alunos.People'),
        ),
    ]
