# Generated by Django 3.2.9 on 2021-11-26 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0024_bills_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bills',
            options={'verbose_name': 'Boleto', 'verbose_name_plural': 'Boletos'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
    ]
