# Generated by Django 3.2.9 on 2021-11-26 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0025_auto_20211126_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.people', verbose_name='Aluno'),
        ),
    ]
