# Generated by Django 3.2.9 on 2021-11-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0026_alter_bills_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='month',
            field=models.CharField(choices=[('janeiro', 'Janeiro'), ('fevereiro', 'Fevereiro'), ('março', 'Março'), ('abril', 'Abril'), ('maio', 'Maio'), ('junho', 'Junho'), ('julho', 'Julho'), ('agosto', 'Agosto'), ('setembro', 'Setembro'), ('outubro', 'Outubro'), ('novembro', 'Novembro'), ('dezembro', 'Dezembro')], default='novembro', max_length=10, verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='val',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='valor'),
        ),
    ]
