# Generated by Django 3.2.9 on 2021-12-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0027_auto_20211126_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='month',
            field=models.CharField(choices=[('janeiro', 'Janeiro'), ('fevereiro', 'Fevereiro'), ('março', 'Março'), ('abril', 'Abril'), ('maio', 'Maio'), ('junho', 'Junho'), ('julho', 'Julho'), ('agosto', 'Agosto'), ('setembro', 'Setembro'), ('outubro', 'Outubro'), ('novembro', 'Novembro'), ('dezembro', 'Dezembro')], default='dezembro', max_length=10, verbose_name='Mês'),
        ),
    ]
