# Generated by Django 3.2.9 on 2021-12-04 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0029_alter_people_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='people',
        ),
    ]
