# Generated by Django 3.2.9 on 2021-12-04 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0001_initial'),
        ('alunos', '0030_remove_bills_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='boletim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boletos.bills'),
        ),
        migrations.DeleteModel(
            name='Bills',
        ),
    ]
