# Generated by Django 3.2.9 on 2021-12-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0002_alter_bills_unique_together'),
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payments',
            unique_together={('boletim', 'month')},
        ),
    ]
