# Generated by Django 3.2.9 on 2022-01-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_alter_payments_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='month',
            field=models.CharField(choices=[('janeiro', 'Janeiro'), ('fevereiro', 'Fevereiro'), ('março', 'Março'), ('abril', 'Abril'), ('maio', 'Maio'), ('junho', 'Junho'), ('julho', 'Julho'), ('agosto', 'Agosto'), ('setembro', 'Setembro'), ('outubro', 'Outubro'), ('novembro', 'Novembro'), ('dezembro', 'Dezembro')], default='janeiro', max_length=10, verbose_name='Mês'),
        ),
    ]
