# Generated by Django 3.2.9 on 2021-12-04 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0030_remove_bills_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=2021, help_text='ex: 2021', verbose_name='Ano da turma')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.people', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
            },
        ),
    ]
