# Generated by Django 3.2.9 on 2021-12-14 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0032_auto_20211203_2227'),
        ('boletos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bills',
            unique_together={('people', 'ano')},
        ),
    ]
