# Generated by Django 3.2.9 on 2022-01-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0002_alter_bills_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='ano',
            field=models.IntegerField(default=2022, help_text='ex: 2022', verbose_name='Ano da turma'),
        ),
    ]
