# Generated by Django 3.2.9 on 2021-12-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0032_auto_20211203_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('segunda-feira', 'Segunda-Feira'), ('terça-feira', 'Terça-Feira'), ('quarta-feira', 'Quarta-Feira'), ('quinta-feira', 'Quinta-Feira'), ('sexta-feira', 'Sexta-Feira')], default='segunda-feira', max_length=20, verbose_name='Dia')),
                ('schedule', models.CharField(choices=[('Manhã', (('m1', 'M1 (07:00 / 08:00)'), ('m2', 'M2 (08:00 / 09:00)'), ('m3', 'M3 (09:00 / 10:00)'), ('m4', 'M4 (10:00 / 11:00)'), ('m5', 'M5 (11:00 / 12:00)'))), ('Tarde/Noite', (('t1', 'T1 (16:00 / 17:00)'), ('t2', 'T2 (17:00 / 18:00)'), ('t3', 'T3 (18:00 / 19:00)'), ('t4', 'T4 (19:00 / 20:00)'), ('t5', 'T5 (20:00 / 21:00)'), ('t6', 'T6 (21:00 / 22:00)')))], default='m1', max_length=2, verbose_name='Horário')),
                ('alunos', models.ManyToManyField(blank=True, help_text='Escolha os alunos da turma e transfira para a tabela da direita.', to='alunos.People')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ('day',),
            },
        ),
    ]
