# Generated by Django 3.2.9 on 2021-12-14 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turmas',
            unique_together={('day', 'schedule')},
        ),
    ]
