# Generated by Django 3.2.9 on 2022-01-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_alter_turmas_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turmas',
            options={'ordering': ('day', 'schedule'), 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
    ]
